# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Marvis
                                 A QGIS plugin
 Tool for visualizing Marxan data output 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-27
        copyright            : (C) 2018 by Joshua Murphy
        email                : jmurphy17@mun.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Marvis class from file Marvis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .marvis import Marvis
    return Marvis(iface)
